name: retouch
description: CLI to keep track of files which have been touched.
version: 1.0.0
repository: https://github.com/virajp/retouch

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  args: 
  path: 
  ansicolor: 
  console: 

dev_dependencies:
  lints:
